import hashlib,json,re
from pathlib import Path
import jsonschema
root=Path.cwd();raw=root/'docs/exec-plans/reviews/HG-044/GENERAL-raw';head='351f0eda41ad492e66115f9ea1e41e3e0f9abf3d'
focused=(raw/'focused.log').read_text();provenance=(raw/'hg043-provenance.log').read_text()
assert re.search(r'79 passed in ',focused),focused
assert re.search(r'39 passed in ',provenance),provenance
captures=[]
for name,command,count in [('focused','PYTHONPATH=<repository>/src PYTHONPYCACHEPREFIX=/private/tmp/hg044-general-pycache /private/tmp/hg044-venv/bin/python -m pytest -q -p no:cacheprovider --basetemp=/private/tmp/hg044-general-tests tests/harness/test_m3_milestone_closure.py',79),('hg043-provenance','PYTHONPATH=<repository>/src PYTHONPYCACHEPREFIX=/private/tmp/hg044-general-pycache /private/tmp/hg044-venv/bin/python -m pytest -q -p no:cacheprovider --basetemp=/private/tmp/hg044-general-provenance tests/harness/test_review_evidence_provenance.py',39)]:
 data=(raw/(name+'.log')).read_bytes();captures.append(dict(check_id=name,command=command,reviewed_head_sha=head,exit_code=0,result='PASS',passed=count,raw_path=str((raw/(name+'.log')).relative_to(root)),raw_sha256=hashlib.sha256(data).hexdigest(),raw_byte_count=len(data)))
(raw/'captures.json').write_text(json.dumps(captures,indent=2)+'\n')
findings=[dict(finding_id='HG044-GENERAL-001',classification='BLOCKER',severity='BLOCKER',priority=1,title='Require executed coverage for every requested regression selector',file='tools/harness/validate_harness.py',start=2648,end=2657,body='The collection oracle verifies that each node matches any required selector, but never that every selector has an executed node. The independently created complete Git fixture passes with transaction_interfaces entirely absent from migrations+transaction_interfaces, and DB shadow isolation entirely absent from unit+DB shadow isolation. Command strings, collection raw/hash/counts, JUnit equality and freshness all remain valid. This contradicts the closure contract forbidding omitted selectors/empty substitutes and permits a fresh integrated regression to claim a required suite it did not execute.',required_change='Require every required selector to have at least one matching collected/executed node. Populate the valid fixture with all requested selectors and add hash-correct collection/JUnit omission negatives that pass freshness and fail the selector-coverage oracle.',evidence_refs=['docs/exec-plans/reviews/HG-044/GENERAL-raw/probe.json','docs/exec-plans/reviews/HG-044/GENERAL-raw/probe.py']),dict(finding_id='HG044-GENERAL-002',classification='NONBLOCKING',severity='NONBLOCKING',priority=3,title='Enforce integer exit-code type consistently',file='tools/harness/validate_harness.py',start=2610,end=2612,body='The guard rejects booleans but accepts JSON 0.0 because Python float zero compares equal to integer zero. The same comparison appears in collection binding. The contract specifies integer zero; the independent probe confirms 0.0 is accepted past the other execution evidence guards. This does not claim a failed exit was accepted.',required_change='Use an exact integer type check for execution and collection exit codes and retain negative tests for floating-point zero.',evidence_refs=['docs/exec-plans/reviews/HG-044/GENERAL-raw/probe.json'])]
refs=['AGENTS.md','.agents/skills/pr-merge-reviewer/SKILL.md','CURRENT_DOCUMENT_INDEX.json','docs/harness/HARNESS_GOVERNANCE_CONTRACT.md','docs/harness/THREAD_RESULT_CONTRACT.md','docs/harness/THREAD_REVIEW_CONTRACT.md','docs/harness/MERGE_GATE.md','docs/harness/M3_CLOSURE_CONTRACT.md','docs/exec-plans/governance/HG-044.yaml','docs/exec-plans/evidence/HG-044/capture-integrity-e748b37.json','docs/exec-plans/evidence/HG-044/DEVELOPMENT_ROUNDS.md','tools/harness/validate_harness.py','tests/harness/test_m3_milestone_closure.py','MILESTONE_CLOSURE.schema.json']
refs += [str(p.relative_to(root)) for p in sorted(raw.iterdir()) if p.is_file()]
review=dict(task_identity='harness-governance-v0.1/HG-044',reviewed_head_sha=head,review_type='GENERAL',status='CHANGES_REQUIRED',findings=findings,review_contract_version='v0.2',protected_base_sha='9268fc8dd8c071c02dc5c698274dbf6fcd112776',summary='Fresh independent GENERAL review requires changes for missing per-selector executed coverage in the integrated regression content oracle. No frozen/runtime/scope/provenance regression was found; lower-severity integer exit-code hardening is also recorded.',evidence_refs=refs,verification=['Inspected actual pinned protected-base diff and governance/result/review/merge contracts independently. Exact 68 declared paths are in scope; no actual M3 instance, task/integration/requirement update, production activation, executable shadow, runtime/migration/CI/frozen change exists.','Verified all 27 index hashes and 161 manifest hashes/byte counts at the reviewed Git tree; all 42 retained raw captures and all eight selected final check bindings; capture-integrity hashes; final e748b37 logs report 79 focused, 869 harness, 232 unit and lint/type/validation/scope/diff PASS. The tested suffix is legal and development evidence is explicitly superseded.','Existing M1/M2 schema branches and definitions are unchanged; all existing validator functions except intended governance scope/orchestration are byte-identical. M1/M2 validate. All 52 named-check contract digests match canonical definitions.','Independently validated 32 recursive integration chains, exact result bytes/hashes, reviews and reachable revisions; every dependency merge precedes consumer base and tested SHA. KL028/KL029 remain absent prospective integrations.','Independent focused pure/Git suite passed 79; HG043 provenance suite passed 39. Complete isolated Git content-oracle probe reproduced omitted requested selectors and float zero acceptance past freshness, regular-blob hashing, counts and JUnit equality. No DB lifecycle was run.'],limitations=['Review binds only the exact original reviewed SHA. A repair requires new selected check evidence and fresh review; CHANGES_REQUIRED is not merge approval.','Independent reviewer ran pure/Git checks only. Applicable unchanged hosted isolated PostgreSQL CI remains separately required at final PR head.','Only GENERAL.json and GENERAL-raw evidence were written; no implementation edit, commit, push, PR or app chat message was made.'])
jsonschema.Draft202012Validator(json.loads((root/'THREAD_REVIEW.schema.json').read_text())).validate(review)
(root/'docs/exec-plans/reviews/HG-044/GENERAL.json').write_text(json.dumps(review,indent=2)+'\n')
print('GENERAL CHANGES_REQUIRED',len(findings),'findings')
