"""Independent M3 content-oracle probe on an isolated synthetic Git fixture."""
import copy
import importlib.util
import json
import tempfile
from pathlib import Path
root=Path.cwd()
spec=importlib.util.spec_from_file_location('review_m3_tests',root/'tests/harness/test_m3_milestone_closure.py')
t=importlib.util.module_from_spec(spec);spec.loader.exec_module(t)
h=t.History(Path(tempfile.mkdtemp(prefix='hg044-general-probe-',dir='/private/tmp'))/'repo')
v=t.v
baseline=v.m3_execution_evidence_errors(h.root,h.payload,h.evaluated,h.evaluated,h.records)
p=copy.deepcopy(h.payload);p['executions'][0]['exit_code']=0.0
float_errors=v.m3_execution_evidence_errors(h.root,p,h.evaluated,h.evaluated,h.records)
rows=[]
for run in h.payload['executions']:
    if run['command'].startswith('uv run pytest -q ') and len(run['command'].removeprefix('uv run pytest -q ').split())>1:
        collection=json.loads((h.root/run['collection']['path']).read_text())
        selectors=run['command'].removeprefix('uv run pytest -q ').split()
        missing=[s for s in selectors if not any(n==s or n.startswith(s+'[') or n.startswith(s+'::') or n.startswith(s+'/') for n in collection['nodeids'])]
        rows.append(dict(command=run['command'],nodeids=collection['nodeids'],missing_selectors=missing))
report=dict(reviewed_head_sha='351f0eda41ad492e66115f9ea1e41e3e0f9abf3d',fixture_root=str(h.root),baseline_errors=baseline,float_exit_code_errors=float_errors,multiple_selector_rows=rows,description='Synthetic fixture generated by committed tests; no actual closure/project evidence. Baseline content validator accepts runs whose raw collection and JUnit omit a requested selector.')
(root/'docs/exec-plans/reviews/HG-044/GENERAL-raw/probe.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
