import hashlib,json,subprocess,xml.etree.ElementTree as ET
from pathlib import Path
from jsonschema import Draft202012Validator
P=Path('/private/tmp/hg047-general-r4');R=Path('/Users/davetian/.codex/worktrees/ffff/KineticLoop');H='b71d2d63f8bc27ab0e905b0be8a0cea5f0122a91';rel='docs/exec-plans/reviews/HG-047/general_round4/'
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()==H
commands={
'interrupted':'PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=src /private/tmp/hg044-venv/bin/python -m pytest -q -p no:cacheprovider tests/harness/test_compact_evidence.py tests/harness/test_local_gate.py tests/harness/test_m3_milestone_closure.py tests/harness/test_review_evidence_provenance.py tests/harness/test_parallel_runner.py --basetemp=/private/tmp/hg047-general-r4/pytest --junitxml=/private/tmp/hg047-general-r4/focused.xml',
 'targeted':'PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=src /private/tmp/hg044-venv/bin/python -m pytest -q -p no:cacheprovider tests/harness/test_review_evidence_provenance.py tests/harness/test_parallel_runner.py tests/harness/test_m3_milestone_closure.py::test_compact_nested_storage_cannot_supply_m3_execution_stdout --basetemp=/private/tmp/hg047-general-r4/targeted-pytest --junitxml=/private/tmp/hg047-general-r4/targeted.xml',
 'parallel':'PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=src /private/tmp/hg047-general-r4/venv/bin/python -m pytest -q -p no:cacheprovider tests/harness/test_parallel_runner.py --basetemp=/private/tmp/hg047-general-r4/locked-parallel-pytest --junitxml=/private/tmp/hg047-general-r4/parallel.xml',
 'validator':'PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=src /private/tmp/hg044-venv/bin/python -m pytest -q -p no:cacheprovider tests/harness/test_validator.py::ValidatorTests::test_ci_prospective_evidence_budget_includes_review_suffix tests/harness/test_validator.py::ValidatorTests::test_ci_review_cannot_repair_preexisting_manifest_in_suffix --basetemp=/private/tmp/hg047-general-r4/validator-pytest --junitxml=/private/tmp/hg047-general-r4/validator.xml'}
records=[]
for key,command in commands.items():
 cases=list(ET.parse(P/(key+'.xml')).iter('testcase'));named=[c for c in cases if c.get('classname')];bad=[c for c in named if any(list(c.iter(t)) for t in ['failure','error','skipped'])]
 if key=='interrupted':
  assert len(named)==373 and len(cases)==374 and not bad
  status,exit_code='INTERRUPTED',130
 elif key=='targeted':
  assert len(named)==64 and len(bad)==7 and all(c.get('classname')=='tests.harness.test_parallel_runner' for c in bad)
  assert '7 failed, 57 passed' in (P/'targeted.log').read_text()
  status,exit_code='FAIL',1
 else:
  assert len(named)=={'parallel':18,'validator':2}[key] and not bad
  assert f'{len(named)} passed' in (P/(key+'.log')).read_text()
  status,exit_code='PASS',0
 records.append({'check':key,'command':command,'status':status,'exit_code':exit_code,'named_cases':len(named),'failed_cases':len(bad),'unnamed_artifacts':len(cases)-len(named),'log':rel+key+'.log','junit':rel+key+'.xml','log_sha256':hashlib.sha256((P/(key+'.log')).read_bytes()).hexdigest(),'junit_sha256':hashlib.sha256((P/(key+'.xml')).read_bytes()).hexdigest()})
assert (P/'authority.log').read_text().strip()=='HARNESS_CHECK_PASS tasks=77 active=74'
records.append({'check':'authority','command':'PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=src /private/tmp/hg044-venv/bin/python tools/harness/validate_harness.py','status':'PASS','exit_code':0,'log':rel+'authority.log'})
(P/'checks.json').write_text(json.dumps({'reviewed_head_sha':H,'checks':records,'component_verification':{'compact_completed_in_interrupted_run':228,'controller_completed_in_interrupted_run':44,'compact_m3_semantics_completed_in_interrupted_run':9,'review_provenance_completed_in_failed_environment_run':39,'nested_m3_completed_in_failed_environment_run':7,'parallel_complete_locked_environment_rerun':18,'new_validator_regressions':2},'dependency_diagnosis':'The shared hg044 environment lacked pytest-xdist and execnet. Child pytest rejected -n 0. All7 failure identities belonged to HG048 runner tests. Rerun18 uses unique venv with exact uv.lock versions and wheel hashes; no source/shared-env changes.','review_probe_failure_retained':{'script':rel+'verify-attempt1.py','log':rel+'verification-attempt1.log','exit_code':1,'reason':'Reviewer expected insertion position corrected after exact parent diff inspection.'},'full_database':'NOT_RUN: mandatory root gate'},indent=2)+'\n')
report=(P/'REPORT.md').read_text().replace('Pending test completion; exact outcomes and command records are appended below before publication.', 'Final independent verification: **18 HG-048 runner tests passed** in the isolated locked environment; **two new validator regressions passed**; authority returned **HARNESS_CHECK_PASS tasks=77 active=74**. The original targeted run remains **FAIL (7 failed, 57 passed)** because the older environment lacked declared xdist/execnet; its 39 provenance and seven nested-M3 cases completed successfully. The overbroad run remains **INTERRUPTED (373 completed passes; exec exit 130)**. Exact commands, statuses and raw log/JUnit hashes are retained in `checks.json`.')
report += '\nThe seven targeted failures were independently diagnosed from raw child output (`unrecognized arguments: -n 0`) and missing distributions in the older shared hg044 environment. A unique temporary venv installs only pytest/xdist and their dependencies at exact committed-lock versions and wheel hashes with `--require-hashes`. All 18 HG048 runner cases then passed without source changes. `targeted.log`/`targeted.xml` preserve every original failure; `parallel.log`/`parallel.xml` hold the successful rerun. `locked-review-requirements.txt` and `dependency-install.log` preserve dependency provenance. The shared environment was not modified.\n'
(P/'REPORT.md').write_text(report)
files=['REPORT.md','checks.json','verify.py','verification.json','verification.log','verify-attempt1.py','verification-attempt1.log','execution_audit.py','execution-verification.json','execution-verification.log','governance-verification.json','targeted.log','targeted.xml','parallel.log','parallel.xml','interrupted.log','interrupted.xml','validator.log','validator.xml','authority.log','finalize.py','locked-review-requirements.txt','dependency-install.log']
refs=['docs/exec-plans/governance/HG-047.yaml','docs/exec-plans/evidence/HG-047/SCOPE.md','docs/exec-plans/evidence/HG-047/round4-7b35dc5/execution.json']+[rel+n for n in files]
review={'task_identity':'harness-governance-v0.1/HG-047','reviewed_head_sha':H,'review_type':'GENERAL','status':'PASS','findings':[{'id':'G-01','classification':'NONBLOCKING','title':'Unicode escape causes ordinary duplicate-key JSON to be rejected','file':'tools/harness/compact_evidence.py','line':129,'description':'Independently reproduced: storage_pairs calls unique before reserved storage identity is established. An ordinary duplicate-key object with literal values remains plain; an equivalent Unicode-escaped value raises evidence-duplicate-key. This is a lossless compatibility limitation, but fails closed, supplies no PASS/provenance bypass, and affects none of the selected or historical artifacts independently retrieved in this review. Classification is freshly assessed, not inherited from the old PASS.','suggested_change':'Prospectively identify reserved storage objects before enforcing storage duplicate-key rejection, preserve nonreserved raw bytes, and add literal/escaped parity coverage while retaining strict envelope rejection.'}],'evidence_refs':refs,'review_contract_version':'v0.2'}
Draft202012Validator(json.loads((R/'THREAD_REVIEW.schema.json').read_text())).validate(review)
(P/'GENERAL.json').write_text(json.dumps(review,indent=2)+'\n')
(P/'files-to-persist.json').write_text(json.dumps(files)+'\n')
print(json.dumps({'reviewed_head_sha':H,'status':'PASS','checks':[{k:r[k] for k in ['check','status','exit_code']} for r in records],'findings':1,'blockers':0},indent=2))
