"""Persistence contracts shared by schema and migration implementations."""

from kineticloop.persistence.immutability import (
    COMMAND_ENTRYPOINTS,
    ENTRYPOINT_BY_ID,
    PROTECTION_BY_ID,
    RELATION_PROTECTIONS,
    RUNTIME_ROLE_NAMES,
    WRITER_ROLE_NAMES,
    CommandEntrypoint,
    CommandMutation,
    DatabaseRole,
    GuardRequirement,
    LockTarget,
    RelationProtection,
    SqlPermission,
    StorageClass,
    WriterGrant,
    permissions_for_role,
    render_permission_sql,
    role_name_for,
)
from kineticloop.persistence.schema_topology import (
    AUTHORITY_ROOT_CONSTRAINTS,
    DEFERRED_REFERENCES,
    LOGICAL_RELATIONS,
    POST_BASE_REFERENCE_PLANS,
    RELATION_BY_ID,
    DeferredReference,
    LogicalRelation,
    NormalizedReferencePlan,
    SchemaTopologyError,
    topological_order,
)

__all__ = [
    "AUTHORITY_ROOT_CONSTRAINTS",
    "COMMAND_ENTRYPOINTS",
    "CommandEntrypoint",
    "CommandMutation",
    "DatabaseRole",
    "DEFERRED_REFERENCES",
    "ENTRYPOINT_BY_ID",
    "GuardRequirement",
    "LOGICAL_RELATIONS",
    "LockTarget",
    "POST_BASE_REFERENCE_PLANS",
    "PROTECTION_BY_ID",
    "RELATION_BY_ID",
    "RELATION_PROTECTIONS",
    "RUNTIME_ROLE_NAMES",
    "DeferredReference",
    "LogicalRelation",
    "NormalizedReferencePlan",
    "RelationProtection",
    "SchemaTopologyError",
    "SqlPermission",
    "StorageClass",
    "WRITER_ROLE_NAMES",
    "WriterGrant",
    "permissions_for_role",
    "render_permission_sql",
    "role_name_for",
    "topological_order",
]
