"""Create only HG041's new task and narrow unstarted consumer refinement."""
import ast
import hashlib
import importlib.util
import json
from pathlib import Path

root = Path.cwd()
here = root / 'docs/exec-plans/evidence/HG-041'
ns = {}
exec((root/'docs/exec-plans/evidence/HG-038/draft.py').read_text().split("db='tests/db/test_protocol_interleavings.py'")[0], ns)
ns['HERE'] = here
check = ns['check']
pu = 'tests/unit/workflow/test_full_action_preparation.py'
db = 'tests/db/test_full_action_preparation.py'
contract = '''Full contract discriminator: kl079-full-actions-v1. Preserve the existing kl076-mechanical-test-v1 F/D/N and TRAINING-only request/output IDs, hashes, runtime and positive regression behavior byte-for-byte. A distinct closed full-action request/profile is selected by the persisted isolated TEST policy, not caller completeness or a fallback flag. Keep legacy requests confined to their original policy domain; the full profile requires exactly ordered TRAINING and NUTRITION and denies legacy certificates even if both proposals exist. Retain existing mechanical rules, units and admitted WORKOUT_ACTUAL evidence: NUTRITION is the fixture fuel TARGET derived from exact N.fuel_units=F.action.minutes*3 and D semantic classes, with no nutrition intake/clinical evidence claim. Its closed parameters are {fuel_units: N.fuel_units, semantic_class: TARGET, units: fixture_units}; its parameters hash is the canonical digest of precisely that object. TRAINING parameters retain F.action and its historical digest. A new NUTRITION-specific S36 binds exact N id/hash plus F/D ids/hashes, action_type=NUTRITION, parameters hash, subject/root/request/revision/attempt/snapshot/context/epoch, manifest id/hash, policy id/hash/runtime version, SEALED source id/hash/ranges/members, actual admitted provenance and computed support/contradiction/association/coverage/consistency/truncation/expiry. Compute both action-specific obligations from actual sealed membership and existing fixed mechanical rules; policy required_members alone cannot establish coverage. Never relabel a TRAINING row or reuse its hash as evidence of NUTRITION applicability. Full TRAINING S36 also binds this same exact F/D/N closure, with distinct full-profile identity; preserve legacy TRAINING rows. Full query_basis_hash digests this exact per-action basis including action type, proposal id/hash, F/D/N, source, manifest and policy; no generic action escape.

Physical representation: one full S37 with singular ref_s36_id anchored to its TRAINING S36, ref_s34_id anchored to N, ref_s35_id=D, ref_s03_id=current execution_basis_event_id, and existing exact manifest/policy/request/attempt FKs. Store closed immutable ordered action_bindings [TRAINING,NUTRITION] in typed_payload, each containing action_type, proposal_id/hash (F for TRAINING, N for NUTRITION), action_parameters_hash, resolution_id/hash and query_basis_hash. Include full contract discriminator and exact required_actions; legacy resolution_hash remains the TRAINING anchor, never proof of another action. Duplicate, missing, extra or reordered bindings deny. Both distinct S36 rows must be loaded by exact subject/id/hash and mechanically reconstructed; JSON references to the additional NUTRITION resolution are not database FKs and must be explicitly verified by the owners. The S37 singular FK cannot be repointed per issuance or used to imply two resolutions. valid_until is finite server minimum of both resolution deadlines, manifest/runtime/policy/source admission bounds; no caller extension. Preserve immutable S37 and S36 histories and return non-executable identities only.

Stage and consumer contract: use existing snapshot/F/D/N forward progression; produce both S36 rows and one full S37 at VALIDATING. AdvanceAttempt keeps its exact six-source map snapshot/fitness/demand/nutrition/resolution/validation, with resolution equal to the TRAINING anchor. No new stage, backward jump or public wire extension. Within transactions.py, extend only exact full-profile _progress_sources COMMIT_READY checks to read/reconstruct both S36 bindings and S37 closure under the existing authenticated current-chain guard; retain legacy branch unchanged. planning_progress.py and workflow/planning_progress.py are read-only. COMMIT_READY must reject partial/foreign/stale/mixed full certificates rather than trusting PASS or column anchor alone. KL079 stops at actual COMMIT_READY; T6 issuance is KL077. KL077 loads this certificate and both action rows, rechecks all current basis/validity/registry/exposure guards and all per-member bindings, then each S42 binds its own ref_s36_id and the shared exact ref_s37_id; S40 content references F or N respectively. Full-path authorization/demand guard must check D.ref_s34_id=F, N.demand_feature_id=D and each member's proposal, not require the singular N anchor to equal D's F. Full semantic validation must consume both bound proposals rather than apply legacy training-action logic to N. No caller membership substitute, raw SQL target seeds, self-PASS, or new clinical/model/production policy.'''
owner = '''Extend only existing deterministic TEST EvidenceResolver and ValidationService in the two deterministic_planning modules and exact restricted fixture preparation/progression support in transactions.py. Proposal/Demand owners and historical legacy ingress remain compatible. New internal requests and immutable models are closed, separately authenticated ProgressIdentity-bound TEST principal/role/subject/policy/environment/current worker; no public command registry, TRANSACTION_OWNER_MATRIX or INTERNAL_ONLY_OPERATIONS edits, arbitrary callbacks, grants or SQL escape. Pure computation and sealed reconstruction occur before coordination; capture is rechecked under existing S01→S27→S02→S29 order, fresh trusted post-lock time, current manifest/epoch/request/revision/attempt/fence/lease/deadline/control/runtime/evidence. Append only S36 or S37 plus own receipt/event/outbox; no production/head/session/P/A/intent success. No model/network waits inside transactions. Existing shared-registry T6/T7 locks remain downstream, no new late S51 lock or frozen lock-order change. ''' + contract
source = '''Every fixture/helper belongs to tests/db/test_full_action_preparation.py or its declared unit file; no undeclared helper, lifecycle, migration or historical task edits. Build source inputs through actual CanonicalViewService SEALED membership, KL078 projection/build, T3 publication, KL024 admission/acquire, KL075 snapshot/forward progression and KL076 F/D/N owners. May register isolated TEST subject/program/policy/environment/runtime and explicitly admitted immutable source inputs; never seed S15/S16, S21-S26, COMMIT_READY, S34-S37 or downstream outputs. Load immutable seed builders only with explicit owned URLs and no imported foreign pytest lifecycle. Preserve tests/db/test_deterministic_planning.py and tests/fixtures/deterministic_planning.json unchanged; run legacy positive behavior in an own-namespace regression trajectory and unchanged hosted full DB CI. New fixture data is tests/fixtures/full_action_preparation.json, a closed mechanical TEST profile with exact units, role/environment/policy/runtime and required actions, never production config. New profile runtime/artifact registration uses actual SafetyRegistryService and existing immutable dependency capability. No rewrite of completed KL076 files. F2 repair uses KL024 structured revision/new attempt under original root budget/deadline then actual snapshot and forward stages, recalculates D2/N2 and both resolutions/full validation; old F1/D1/N1/resolutions/certificates remain immutable and deny mixed closure.'''
checks = [
check('full_action_contract_pu',pu,'test_contract','Closed full-profile request/schema; exact action discriminators/parameters/proposal hashes/ordered bindings and singular TRAINING anchor. Wrong role/principal/subject/policy/environment/action, caller PASS/completeness and legacy fallback deny. Existing 39 public wires/owners/internal-only operations unchanged.'),
check('full_action_resolution_pu',pu,'test_resolution_semantics','Compute actual TRAINING and NUTRITION action-specific source coverage/consistency/association/truncation/expiry from sealed input shape and existing mechanical F/D/N. N TARGET units never ACTUAL; reject missing/extra/duplicate/mixed/cross-action hashes, source membership/policy-only coverage, contradiction/retraction/unknown/future evidence. Exact equality at minimum expiry denies as PU, never mislabeled DC.'),
check('full_action_namespace_pu',pu,'test_namespace','Validate exact task/SHA/resolved-root full label namespace and all nested bootstrap/reset/cleanup before first real lifecycle; reject malformed/foreign/ambient/default targets. Existing merged fixtures remain read-only.'),
check('full_action_owner_pipeline_dc',db,'test_owner_pipeline','Actual real-PG source-to-F/D/N→two distinct full action S36→one full S37→actual COMMIT_READY. Assert exact columns/FKs/payload hashes/source ranges/membership/ordered per-action proposal and resolution bindings, finite minimum expiry and receipt/event/outbox/stage chain. S37 TRAINING anchor and N/D column anchors persist unchanged; extra N resolution is owner-verified by ID/hash, not invented FK. No target SQL seeds or caller self-PASS.'),
check('full_action_basis_denials_dc',db,'test_basis_denials','Real owners and actual COMMIT_READY independently reject wrong action/parameters/proposal/subject/policy/manifest/source/runtime, missing/duplicate/reordered/foreign resolution/member, stale F/D/N, partial coverage, contradiction/truncation/retraction, current execution basis/epoch/revision/attempt/fence/lease/deadline/control loss and source/runtime revocation/expiry. Assert exact zero row/bookkeeping/stage/pointer effects; current-state denial reached after valid ingress, no earlier key/lifecycle error substitute. Fresh trusted post-lock time crosses expiry with observed bounded blocker, distinct before/after cases; equality only PU.'),
check('full_action_replay_atomicity_dc',db,'test_replay_and_atomicity','Both action owners and full validation return exact historical immutable IDs/hashes on ACK-loss replay non-executable; changed same-key payload conflicts. Concurrent duplicate contenders serialized through existing locks produce exactly one each S36/S37 plus receipt/event/outbox. Observed pg_blocking_pids/barriers/future timeouts and injected failures after output/before bookkeeping prove full rollback. No sleep establishes order, no output relabel or authority replay.'),
check('full_action_repair_dc',db,'test_f2_repair','Actual same-root KL024 revision/new attempt and guarded forward stages create F2/D2/N2, both new S36 and full S37. Old D1/N1/resolutions/certificates deny at validation and COMMIT_READY, remain byte-identical; root budget/deadline/history unchanged, no backward jump or terminal reopening. KL077 later proves T6 denial separately.'),
check('full_action_legacy_no_authority_dc',db,'test_legacy_and_no_authority','Preserve actual legacy TRAINING pipeline and exact historical identities/positive oracles under own namespace; full profile cannot downgrade to legacy single resolution/certificate. No S38-S45/head/P/A/session/binding/production authority/intent success; preparation and COMMIT_READY are non-executable. Production/shadow/principal/environment negatives have zero effects, planned quantities never fill actual facts.'),
check('full_action_suite_dc',db,'','Full own real-PG suite without skipped/xfail/zero collection, exact namespace/current_database/migration/cleanup/bounded timing/persisted IDs and raw logs. Existing unchanged hosted legacy DB/quality/selected-task gates PASS before normal merge.')]
ns['define']('KL-079','Full TEST action evidence and validation preparation',['KL-076','KL-075','KL-078','KL-024','KL-019','KL-017','KL-074'],['src/kineticloop/workflow/deterministic_planning.py','src/kineticloop/persistence/deterministic_planning.py','src/kineticloop/persistence/transactions.py',pu,db,'tests/fixtures/full_action_preparation.json','docs/contracts/full_action_preparation.md'],['transaction_interfaces','user_coordination'],checks,['T6-PREPARATION','T5'],['S01','S02','S03','S04','S05','S15','S16','S24','S26','S27','S28','S29','S34','S35','S36','S37','S49','S50'],['INV-01','INV-02','INV-03','INV-04','INV-05','INV-09','INV-10','INV-11','INV-12','INV-13','INV-14','INV-16','INV-17'],dict(goal='Produce the missing action-specific NUTRITION evidence and exact full member validation closure, preserving legacy TRAINING and stopping at COMMIT_READY before downstream issuance.',owner=owner,source=source,done='Each named PU/DC oracle passes from actual owner inputs to two action resolutions/full validation/COMMIT_READY, preserving legacy regression behavior and immutable replay/repair. Full T6/T7 and KL027 integration are future dependent work; no circular downstream self-gate.'))
bp = root/'KineticLoop_Harness_Backlog_v0.2.json'; b = json.loads(bp.read_text()); tasks = {t['id']: t for t in b['tasks']}
assert 'KL-079' not in tasks
new = json.loads((here/'KL-079.definition.draft.json').read_text())
new['context_files'] = ns['AUTHORITY'] + ['docs/exec-plans/evidence/HG-041/PREPARATION.md','src/kineticloop/workflow/deterministic_planning.py','src/kineticloop/persistence/deterministic_planning.py','src/kineticloop/persistence/transactions.py','src/kineticloop/persistence/planning_progress.py','src/kineticloop/workflow/planning_progress.py','src/kineticloop/persistence/metadata.py','src/kineticloop/persistence/schema_topology.py','src/kineticloop/persistence/protocol_execution.py','docs/contracts/deterministic_planning.md'] + [f'docs/exec-plans/completed/{d}_RESULT.yaml' for d in new['depends_on']]
b['tasks'].append(new); b['task_count']=len(b['tasks']); b['active_task_count']=sum(t['status']!='SUPERSEDED' for t in b['tasks'])
old=tasks['KL-077']; assert old['status']=='NOT_STARTED'
old['depends_on'].append('KL-079')
entry='KL079 normally merged with exact full action S36/S37 producer contract and actual COMMIT_READY evidence; verify both TRAINING and NUTRITION bindings before scheduling, never infer applicability from shared hashes.'
old['entry_conditions'].append(entry)
old['context_files'] += ['docs/exec-plans/completed/KL-079_RESULT.yaml','docs/contracts/full_action_preparation.md','docs/exec-plans/evidence/HG-041/PREPARATION.md']
bp.write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n')
p=root/'docs/exec-plans/active/KL-079.md'; text=(here/'KL-079.packet.draft.md').read_text(); start=text.index('\n- 05_KineticLoop_',text.index('## Read first')); end=text.index('\n## Frozen impact map'); text=text[:start]+'\n'+''.join('- '+x+'\n' for x in new['context_files'])+'\n'+text[end:]; p.write_text(text)
p=root/'docs/exec-plans/active/KL-077.md'; text=p.read_text().replace('- KL-074\n\n### Conditional dependencies','- KL-074\n- KL-079\n\n### Conditional dependencies',1).replace('## Read first','- '+entry+'\n\n## Read first',1).replace('- docs/exec-plans/completed/KL-074_RESULT.yaml','- docs/exec-plans/completed/KL-074_RESULT.yaml\n- docs/exec-plans/completed/KL-079_RESULT.yaml\n- docs/contracts/full_action_preparation.md\n- docs/exec-plans/evidence/HG-041/PREPARATION.md',1)
text=text.replace('Missing upstream capability is a separately scoped prerequisite, never a raw output seed workaround.', 'KL079 is the separately scoped full action evidence prerequisite. '+contract+' Missing upstream capability is a separately scoped prerequisite, never a raw output seed workaround.',1); p.write_text(text)
vpath=root/'tools/harness/validate_harness.py'; text=vpath.read_text().replace("'KL-077', 'KL-078'}","'KL-077', 'KL-078', 'KL-079'}").replace("'KL-077', 'KL-078'})","'KL-077', 'KL-078', 'KL-079'})")
for constant in ['M3_NEXT_WAVE_DEFINITION_HASHES','M3_NEXT_WAVE_PACKET_HASHES']:
 tree=ast.parse(text); node=next(n for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id==constant for t in n.targets)); values=ast.literal_eval(node.value)
 for name,task in [('KL-077',old),('KL-079',new)]:
  raw=json.dumps(task,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode() if 'DEFINITION' in constant else (root/f'docs/exec-plans/active/{name}.md').read_bytes(); values[name]=hashlib.sha256(raw).hexdigest()
 lines=text.splitlines(keepends=True); lines[node.lineno-1:node.end_lineno]=[constant+' = '+repr(values)+'\n']; text=''.join(lines)
vpath.write_text(text)
spec=importlib.util.spec_from_file_location('hg041v',vpath); v=importlib.util.module_from_spec(spec); spec.loader.exec_module(v)
p=root/'KineticLoop_Harness_Traceability_v0.3.json'; trace=json.loads(p.read_text()); trace['tasks']=[v.traceability_projection(old) if t['id']=='KL-077' else t for t in trace['tasks']]; trace['tasks'].append(v.traceability_projection(new)); p.write_text(json.dumps(trace,ensure_ascii=False,indent=2)+'\n')
p=root/'HARNESS_DOCUMENT_MANIFEST.json'; m=json.loads(p.read_text()); m['files'].append({'path':'docs/exec-plans/active/KL-079.md','bytes':0,'sha256':'0'*64}); p.write_text(json.dumps(m,indent=2)+'\n')
p=root/'06_KineticLoop_Project_Plan_v0.6_HARNESS_HARDENED.md'; p.write_text(p.read_text()+'''\n\n## Full action evidence prerequisite — HG041\n\nKL079 is a fresh NOT_STARTED task for owner-produced TRAINING and NUTRITION\naction evidence and an exact full validation certificate through COMMIT_READY.\nS37 retains its singular TRAINING FK anchor and carries closed immutable per-action\nbindings; owners verify the additional resolution identity explicitly. KL077 waits\nfor its normal merge and consumes each binding at T6, preserving ordinary pause\nand current T7 oracles. KL027 already depends transitively on KL079 through KL077.\nKL076 completed definitions/results remain immutable historical input. No product,\nM3, release, production or downstream implementation closure is claimed.\n''')
print('HG041_DEFINITIONS_CREATED')
