"""Build prospective definitions exclusively within HG040 evidence."""
import json
from pathlib import Path

root=Path.cwd(); here=root/'docs/exec-plans/evidence/HG-040'
source=(root/'docs/exec-plans/evidence/HG-038/draft.py').read_text()
ns={}; exec(source.split("db='tests/db/test_protocol_interleavings.py'")[0],ns)
ns['HERE']=here
pu='tests/unit/persistence/test_preparation.py'; db='tests/db/test_preparation.py'
check=ns['check']
checks=[
check('preparation_revision_pu',pu,'test_server_revision','Exact RecordProjection supplies immutable server-owned S21 revision and provenance bound to authenticated subject/kind/engine/basis/window/content/computation identity. Caller revision/provenance override rejects before mutation; unchanged input returns identical identity, changed content under same identity conflicts, changed basis creates new immutable revision identity. REQUIRED_FIELDS stays complete; no caller column permission or global required-field relaxation.'),
check('preparation_capability_pu',pu,'test_exact_capabilities','Actual gateway permits only respective RecordProjection S21/S22 and BuildManifest S23 surfaces with verified exact basis. Foreign owner/table/column, fabricated lock inventory, raw SQL access, SUBJECT translation, missing typed basis and unguarded callback inserts fail closed. Existing public wire schema, 39-command matrix, PREPARATION boundaries and execute_command rejection remain unchanged; S34-S37 workflow path is untouched.'),
check('preparation_namespace_pu',pu,'test_namespace','Before first real lifecycle prove exact task/SHA/resolved-root namespace derivation and every nested bootstrap/reset/cleanup validation; peer root, malformed SHA/digest, wrong label, arbitrary/ambient/default/foreign project/database deny before destructive entry. bootstrap_two_phase receives own selected lifecycle and finally cleanup revalidates it.'),
check('preparation_owner_pipeline_dc',db,'test_owner_pipeline','Real PG CanonicalViewService.begin_build/write_candidate/complete_factset/seal_factset produces exact actual SEALED S15 from registered TEST subject/program/policy and admitted immutable source inputs. Actual RecordProjection records S21 and complete S22 positive plus collection/absence dependencies atomically; BuildManifest produces complete BUILDING then READY S23 under exact local build ownership. Exact persisted hashes/refs/roles/artifact closure derive from these inputs, then actual ProtocolExecutionService.publish T3 produces S24/S25 plus S01 generation/pointer and receipt/event/outbox once. No S15/S16, S21/S22/S23 or S24/S25 output seeds. Every preparation commit leaves S01 generation/frontier/epoch/pointers and receipt/event/outbox unchanged; only actual T2 seal/T3 may advance their frozen state.'),
check('preparation_basis_denials_dc',db,'test_basis_denials','Actual real PG owner gateways reject cross-subject/nonexistent/nonsealed S15, missing/null/foreign FACTSET references or dependencies, wrong projection parent, incomplete/duplicate role closure, wrong policy/program/artifacts and exact source hash conflict with zero new rows/changed rows. Cover BUILDING, READY and SEALED source states produced by actual builders, never raw status seeds. Exact input validation is exclusive to S22/S23 under their owners, not a blanket FK exemption. Independently show missing/stale epoch/frontier/factset/program/policy/dependency/validity/revoked artifact causes actual T3 denial with zero target/generation/receipt/event/outbox effects; stale preparation cannot be relabeled current.'),
check('preparation_immutable_replay_dc',db,'test_immutable_replay','ACK-loss retry returns exact historical projection/dependency/build identities with no mutation or current/execution authority. Changed same-key content conflicts. Byte-identical S21/S22 and READY/PUBLISHED S23 candidate history survives replay; caller revision injection, updates/dependency replacement, READY basis/epoch relabeling, terminal reopening and unauthorized generic preparation mutations reject. T3 replay retains historical original IDs and cannot repoint S01; subsequent independent publication rechecks current basis.'),
check('preparation_duplicate_rollback_dc',db,'test_duplicate_rollback','Real PG same-computation and same-build duplicate contenders with bounded Events/futures and observed pg_blocking_pids produce one immutable result/dependency closure/build and no overwrite. Exact S23 local locks serialize BUILDING completion; READY candidate cannot change. Inject failure after S21, midway S22 and before/after READY transition then assert full transaction rollback including unchanged S01/receipt/event/outbox. Actual T3 rollback assertions remain enforced. No sleeps establish ordering, no coordination/external waits inside preparation.'),
check('preparation_no_authority_dc',db,'test_no_authority','Preparation holds neither S01 nor SafetyRegistry coordination locks, writes no generation/head/P/A/session/binding/intent success, and grants no execution/production authority. An observed S01 blocker does not block independent immutable preparation; actual T3 uses unchanged shared registry then S01 ordering and rejects stale captured basis after guarded owner input update. Wrong TEST principal/policy/environment and PRODUCTION/SHADOW attempts through fixture ingress reject with zero effects. Provider/network calls absent; planned values never populate actual facts.'),
check('preparation_suite_dc',db,'','Entire own real-PG preparation suite runs without skips/xfail/zero collection. Namespace inventory/current_database/migration revision/persisted source/output IDs/cleanup/deadlines and raw logs recorded. Full legacy tests/db regressions run only through existing unchanged hosted CI on fresh VM; all normal quality and selected-task merge gates pass before normal merge.'),
]
owner='''Repair existing T3 preparation capabilities only, through exact typed trusted ingress in src/kineticloop/persistence/preparation.py and internal restricted gateway support in transactions.py. Require separately authenticated trusted TEST fixture principal bound to exact registered subject/policy/environment, never wire-supplied authority. No public wire/registry/matrix change. Preserve Boundary.PREPARATION and execute_command rejection. RecordProjection inserts immutable S21 with server-owned revision (baseline revision=1 for a new immutable computation identity, never caller-controlled or re-used for different content) and durable canonical provenance; S22 complete dependency closure is recorded atomically with its S21 result. The server reconciles required revision completeness only within this exact insertion; caller revision and provenance injection reject, REQUIRED_FIELDS/metadata and arbitrary column capabilities remain unchanged. Same subject/kind/basis natural computation identity is immutable; bind engine/window/content in provenance so reuse conflicts rather than overwrites. Exact same-subject SEALED S15 inputs are read/verified inside short independent owner transaction, never fabricated locked_ids or generic FK exemption. BuildManifest may lock only exact S23 build row to complete BUILDING to READY; immutable captured S15/frontier/epoch/program/policy/projection/artifact closure cannot be relabeled. READY/PUBLISHED candidate mutation and terminal reopening reject. New basis creates a new build identity. Computation occurs before persistence, no external/model/network waits in any transaction; no S01/registry coordination for preparation. T3 remains sole publication owner with all current-basis/registry/time rechecks and frozen lock order unchanged. Existing unrelated preparation callbacks remain compatible within unchanged capabilities, but cannot bypass exact S21/S22/S23 basis/revision/immutability guards. No arbitrary permissions, SQL/cursor escape, SUBJECT translation or schema/role grant.'''
source_boundary='''Source fixtures reside only in tests/db/test_preparation.py, including every indispensable helper; no undeclared fixture/helper module may be written. May register isolated TEST subject/policy/environment/program, artifacts/dependencies and explicitly admitted immutable evidence/admission/mapping/catalog inputs needed by CanonicalViewService. Every S15/S16 build/member/completion/seal is produced by actual CanonicalViewService with separately authenticated BuilderIdentity, every S21/S22 by RecordProjection, every S23 BUILDING/READY by BuildManifest, and S24/S25 by actual ProtocolExecutionService.publish. Never use legacy seed_inputs that truncates/replica-disables FK checks and raw-seeds target outputs. No output SQL seeds, raw current factset/head/epoch/frontier mutation or fabricated source validation. For raced input/frontier/epoch changes use merged exact AcceptFactRevision owner recipe and actual seal; artifacts revoked through actual SafetyRegistryService. Candidate hashes and closure values compute from exact persisted source identities, policy role list and artifact closure, never fabricated PASS labels. Stop at actual T3 publication; no KL076 F/D/N/S34-S37, KL077 P/A/T7 or downstream execution implementation. Existing publication source is read-only and tests must fail on actual guards rather than weakening it.'''
ns['define']('KL-078','Source-bound projection and manifest preparation repair',
 ['KL-017','KL-019','KL-022','KL-023','KL-074'],
 ['src/kineticloop/persistence/transactions.py','src/kineticloop/persistence/preparation.py',pu,db,'docs/contracts/preparation.md'],
 ['transaction_interfaces'],checks,['T3-PREPARATION','T3'],
 ['S01','S02','S03','S04','S15','S16','S21','S22','S23','S24','S25','S49','S51'],
 ['INV-03','INV-04','INV-05','INV-06','INV-07','INV-10','INV-16','INV-17'],
 dict(goal='One coherent upstream repair enabling immutable owner-produced projection/dependency/build from actual sealed inputs, independent of KL076 F/D/N and downstream execution.',owner=owner,source=source_boundary,done='Actual owner-driven CanonicalViewService → RecordProjection → BuildManifest → T3 succeeds with immutable source binding and every denial, replay, duplicate, rollback and no-authority oracle; no new product/layer/release evidence is inferred.'))
p=here/'KL-078.definition.draft.json'; task=json.loads(p.read_text())
task['context_files']=[x for x in task['context_files'] if x not in ['docs/exec-plans/evidence/HG-038/PREPARATION.md','src/kineticloop/persistence/planning.py']]
task['context_files'] += ['docs/exec-plans/evidence/HG-040/PREPARATION.md','src/kineticloop/persistence/metadata.py','src/kineticloop/persistence/factsets.py','src/kineticloop/protocol/factsets.py']
p.write_text(json.dumps(task,indent=2)+'\n')
p=here/'KL-078.packet.draft.md'; text=p.read_text().replace('- docs/exec-plans/evidence/HG-038/PREPARATION.md','- docs/exec-plans/evidence/HG-040/PREPARATION.md').replace('- src/kineticloop/persistence/planning.py\n','')
text=text.replace('- docs/contracts/protocol_execution.md','- docs/contracts/protocol_execution.md\n- src/kineticloop/persistence/metadata.py\n- src/kineticloop/persistence/factsets.py\n- src/kineticloop/protocol/factsets.py')
p.write_text(text)
